// src/components/Sidebar.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { storeToRefs } from 'pinia'
import { Bars3Icon, ChevronDownIcon, ChevronUpIcon, ExclamationCircleIcon } from '@heroicons/vue/24/outline'
import { useUiStore } from '../stores/ui'

interface NavItem {
  id: number
  icon: string
  text: string
  path?: string
  children?: NavItem[]
}

const navItems: NavItem[] = [
  { id: 1, icon: '🏠', text: '主控台', path: '/' },
  {
    id: 2,
    icon: '🤖',
    text: '我的工具',
    children: [
      { id: 21, icon: '🔑', text: 'Base64', path: '/tools/base64' },
      { id: 22, icon: '📄', text: 'JSON Formatter', path: '/tools/json-formatter' },
      { id: 23, icon: '🖥️', text: 'HTML Previewer', path: '/tools/html-previewer' },
      { id: 24, icon: '📜', text: 'Markdown Previewer', path: '/tools/markdown-previewer' },
      { id: 25, icon: '📱', text: 'QRCode Previewer', path: '/tools/qrious' },
      { id: 26, icon: '🔐', text: 'JWT Decoder', path: '/tools/jwt-decoder' },
    ],
  },
  { id: 3, icon: '💾', text: '存檔歷史', path: '/history' },
]

const route = useRoute()
const uiStore = useUiStore()
const { isSidebarCollapsed } = storeToRefs(uiStore)
const expandedItemIds = ref<number[]>([2])
const appVersion = __APP_VERSION__

const toggleSidebar = () => {
  uiStore.toggleSidebar()
}

const itemHasActiveChild = (item: NavItem) => {
  if (!item.children) {
    return false
  }

  return item.children.some((child) => route.path === child.path)
}

const isExpanded = (itemId: number) => expandedItemIds.value.includes(itemId)

const toggleExpanded = (itemId: number) => {
  if (isExpanded(itemId)) {
    expandedItemIds.value = expandedItemIds.value.filter((id) => id !== itemId)
    return
  }

  expandedItemIds.value = [...expandedItemIds.value, itemId]
}

const navContainerClass = computed(() => ['sidebar', { collapsed: isSidebarCollapsed.value }])
</script>

<template>
  <nav :class="navContainerClass">
    <div class="sidebar-header">
      <button class="toggle-button" @click="toggleSidebar" type="button" aria-label="切換側邊欄">
        <Bars3Icon style="width: 20px; height: 20px" />
      </button>
    </div>

    <ul class="nav-list">
      <li v-for="item in navItems" :key="item.id" class="nav-item">
        <RouterLink
          v-if="item.path"
          :to="item.path"
          class="nav-link-content"
          active-class="active"
          :class="{ active: itemHasActiveChild(item) }"
          :exact-active-class="item.path === '/' ? 'active' : ''"
        >
          <span class="icon">{{ item.icon }}</span>
          <span class="text">{{ item.text }}</span>
        </RouterLink>

        <div
          v-else
          class="nav-link-content"
          :class="{ active: itemHasActiveChild(item) }"
          @click="toggleExpanded(item.id)"
        >
          <span class="icon">{{ item.icon }}</span>
          <span class="text">{{ item.text }}</span>
          <span v-if="item.children && !isSidebarCollapsed" class="submenu-toggle">
            <ChevronUpIcon v-if="isExpanded(item.id)" style="width: 16px; height: 16px" />
            <ChevronDownIcon v-else style="width: 16px; height: 16px" />
          </span>
        </div>

        <ul v-if="item.children && isExpanded(item.id)" class="sub-menu">
          <li v-for="child in item.children" :key="child.id" class="nav-item sub-item">
            <RouterLink
              :to="child.path || '/'"
              class="nav-link-content sub-link"
              active-class="active"
            >
              <span class="icon">{{ child.icon }}</span>
              <span class="text">{{ child.text }}</span>
            </RouterLink>
          </li>
        </ul>
      </li>
    </ul>

    <div class="sidebar-footer">
      <span v-if="!isSidebarCollapsed">版本 {{ appVersion }}</span>
      <a
        href="https://github.com/fujimmy/MyTools/issues"
        target="_blank"
        rel="noopener noreferrer"
        class="issue-button"
        title="回報問題"
        data-testid="issue-report-button"
      >
        <ExclamationCircleIcon style="width: 20px; height: 20px" />
        <span v-if="!isSidebarCollapsed">回報 Issue</span>
      </a>
    </div>
  </nav>
</template>

// src/components/Sidebar.tsx
// src/components/Sidebar.tsx
import React, { useState } from 'react'; // 引入 useState
import { FiMenu } from 'react-icons/fi';
// 引入箭頭圖標用於子菜單收合
import { FiChevronDown, FiChevronUp } from 'react-icons/fi';
import { FiAlertCircle } from 'react-icons/fi';
import { NavLink } from 'react-router-dom';

// 1. 更新介面：NavItem 可以包含一個子項目陣列
interface NavItem {
  id: number;
  icon: string;
  text: string;
  path?: string; // 主項目可能沒有 path
  children?: NavItem[]; // 可選的子項目陣列
}

interface SidebarProps {
  isCollapsed: boolean;
  toggleSidebar: () => void;
}

// 2. 更新導航數據：為 '我的工具' 添加子項目
const navItems: NavItem[] = [
  { id: 1, icon: '🏠', text: '主控台', path: '/' },
  {
    id: 2,
    icon: '🤖',
    text: '我的工具',
    // 注意：主項目通常沒有 path，或者 path 指向一個摘要頁面
    children: [
      { id: 21, icon: '🔑', text: 'Base64', path: '/tools/base64' },
      { id: 22, icon: '📄', text: 'JSON Formatter', path: '/tools/json-formatter' },
      { id: 23, icon: '🖥️', text: 'HTML Previewer', path: '/tools/html-previewer' },
      { id: 24, icon: '📜', text: 'Markdown Previewer', path: '/tools/MarkdownPreviewer' },
      { id: 25, icon: '📜', text: 'QRCode Previewer', path: '/tools/QRious' },
      { id: 26, icon: '🔐', text: 'JWT Decoder', path: '/tools/jwt-decoder' }
    ]
  },
  { id: 3, icon: '💾', text: '存檔歷史', path: '/history' },
  { id: 4, icon: '⚙️', text: '設置', path: '/settings' },
];

// 3. (新增) 子組件：處理單個導航項目的渲染和展開/收合邏輯
interface SidebarItemProps {
  item: NavItem;
  isSidebarCollapsed: boolean;
}

const SidebarItem: React.FC<SidebarItemProps> = ({ item, isSidebarCollapsed }) => {
  // 狀態：追蹤當前項目是否展開
  const [isExpanded, setIsExpanded] = useState(false);

  // 檢查是否有子項目
  const hasChildren = item.children && item.children.length > 0;

  const handleClick = (e: React.MouseEvent) => {
    if (hasChildren) {
      // 阻止 NavLink 執行預設的跳轉行為
      e.preventDefault();
      setIsExpanded(!isExpanded);
    } else if (item.path) {
      // 否則，執行導航邏輯 (未來使用 React Router)
      console.log(`Navigating to: ${item.path}`);
    }
  };

  const navContent = (
    <>
      <span className="icon">{item.icon}</span>
      <span className="text">{item.text}</span>
      {hasChildren && !isSidebarCollapsed && (
        <span className="submenu-toggle">
          {isExpanded ? <FiChevronUp size={16} /> : <FiChevronDown size={16} />}
        </span>
      )}
    </>
  );

  return (
    <li className="nav-item">
      {/* 判斷是否有 path。如果有 path，就使用 NavLink */}
      {item.path ? (
        <NavLink
          to={item.path}
          className={({ isActive }) =>
            `nav-link-content ${isActive ? 'active' : ''}` // 新增 'active' 類別
          }
          onClick={handleClick}
          end={item.path === '/'} // 確保只有根路徑精確匹配時才被視為 active
        >
          {navContent}
        </NavLink>
      ) : (
        // 如果沒有 path (純粹的父級菜單)，使用 div
        <div className="nav-link-content" onClick={handleClick}>
          {navContent}
        </div>
      )}

      {/* 子菜單渲染 */}
      {hasChildren && isExpanded && (
        <ul className="sub-menu">
          {item.children!.map(child => (
            <li key={child.id} className="nav-item sub-item">
              {/*
          錯誤：這裡使用了普通的 div 元素
          <div className="nav-link-content sub-link">
          
          修正：使用 NavLink 才能實現路由跳轉！
        */}
              <NavLink
                to={child.path!} // 確保子項目有 path
                className={({ isActive }) =>
                  `nav-link-content sub-link ${isActive ? 'active' : ''}` // 啟用選中高亮
                }
              >
                <span className="icon">{child.icon}</span>
                <span className="text">{child.text}</span>
              </NavLink>
            </li>
          ))}
        </ul>
      )}
    </li>
  );
};


// 4. Sidebar 主組件：使用新的 SidebarItem
const Sidebar: React.FC<SidebarProps> = ({ isCollapsed, toggleSidebar }) => {
  return (
    <nav className={`sidebar ${isCollapsed ? 'collapsed' : ''}`}>

      {/* 1. 側邊欄頂部的切換按鈕 */}
      <div className="sidebar-header">
        <button className="toggle-button" onClick={toggleSidebar}>
          <FiMenu size={20} />
        </button>
      </div>

      {/* 2. 導航列表：使用 SidebarItem 渲染每個項目 */}
      <ul className="nav-list">
        {navItems.map(item => (
          <SidebarItem
            key={item.id}
            item={item}
            isSidebarCollapsed={isCollapsed}
          />
        ))}
      </ul>

      {/* 3. 底部區域 */}
      <div className="sidebar-footer">
        {!isCollapsed && <span>版本 {__APP_VERSION__}</span>}
        <a
          href="https://github.com/fujimmy/MyTools/issues"
          target="_blank"
          rel="noopener noreferrer"
          className="issue-button"
          title="回報問題"
          data-testid="issue-report-button"
        >
          <FiAlertCircle size={20} />
          {!isCollapsed && <span>回報 Issue</span>}
        </a>
      </div>

    </nav>
  );
};

export default Sidebar;
